#!/bin/bash
#
#  curl commands to reload the data from the previous tutorial
#
#
set -e
export $(cat .env | grep "#" -v)

curl -G -X GET 'http://localhost:'"${ORION_LD_PORT}"'/ngsi-ld/v1/entities/urn:ngsi-ld:Device:temperature002' \
    -H 'fiware-service: openiot' \
    -H 'fiware-servicepath: /'  \
    -H 'Link: <'"${JSONLD}"'>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' | jq .


