#!/bin/bash
#
#  curl commands to reload the data from the previous tutorial
#
#

export $(cat .env | grep "#" -v)
set -e
echo -e 'Seting temperature:' "${1}"

curl -L -X POST 'http://localhost:'"${IOTA_SOUTH_PORT}"'/iot/d?k='"${TemperatureSensor_API}"'&i=temperature002' \
    -H 'Content-Type: text/plain' \
    --data-raw 't|'"${1}"''

curl -L -X GET 'http://localhost:1026/ngsi-ld/v1/entities/urn:ngsi-ld:Device:temperature002' \
    -H 'NGSILD-Tenant: openiot' \
    -H 'Link: <'"${JSONLD}"'>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
    -H 'Accept: application/json'|jq .
