#!/bin/bash
#
#  curl commands to reload the data from the previous tutorial
#

set -e
export $(cat .env | grep "#" -v)

curl -L -X POST 'http://localhost:'"${ORION_LD_PORT}"'/ngsi-ld/v1/subscriptions/' \
-H 'Content-Type: application/ld+json' \
-H 'NGSILD-Tenant: openiot' \
--data-raw '{
  "description": "Notify me of all changes",
  "type": "Subscription",
  "entities" : [{"type": "TemperatureSensor"}],
  "watchedAttributes": ["temperature"],
  "notification": {
    "attributes": ["temperature"],
    "format": "normalized",
    "endpoint": {
      "uri": "http://tonowhere",
      "accept": "application/json"
    }
  },
   "@context": "'"${JSONLD}"'"
}'

curl -X GET \
'http://localhost:'"${ORION_LD_PORT}"'/ngsi-ld/v1/subscriptions/' \
-H 'NGSILD-Tenant: openiot' |jq .