#!/bin/bash
#
#  curl commands to reload the data from the previous tutorial
#

set -e
export $(cat .env | grep "#" -v)
echo -e "Testing subscription for UltraLight"
./provition-DummyUltraTemperature002
./settemperature002 10
./subscribeQuantumUltra
./settemperature002 14

curl -X GET \
'http://localhost:'"${ORION_LD_PORT}"'/ngsi-ld/v1/subscriptions' \
-H 'NGSILD-Tenant: openiot' |jq .